apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp-rc
spec:
  replicas: 3
  selector:
    app: myjavaapp
    version: 2.3.1
  template:
    metadata:
      labels:
        app: myjavaapp
        version: 2.3.1
    spec:
      containers:
      - name: myjavaapp-container
        image: maha4iac/myonlinebooking:1
        ports:
        - containerPort: 8080
